#!/bin/bash
set -e
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
IMG_DIR="$SCRIPT_DIR/images"
mkdir -p "$IMG_DIR"
echo "Downloading 36 images into $IMG_DIR..."

echo "  collage-jokulsarlon.jpg..."
curl -L -s -o "$IMG_DIR/collage-jokulsarlon.jpg" "https://loremflickr.com/1200/800/jokulsarlon"
echo "  collage-diamond-beach.jpg..."
curl -L -s -o "$IMG_DIR/collage-diamond-beach.jpg" "https://loremflickr.com/1200/800/iceberg,beach"
echo "  route-hero.jpg..."
curl -L -s -o "$IMG_DIR/route-hero.jpg" "https://loremflickr.com/1200/800/iceland,road"
echo "  d0-hero-reykjavik.jpg..."
curl -L -s -o "$IMG_DIR/d0-hero-reykjavik.jpg" "https://loremflickr.com/1200/800/reykjavik"
echo "  d0-strip-hallgrimskirkja.jpg..."
curl -L -s -o "$IMG_DIR/d0-strip-hallgrimskirkja.jpg" "https://loremflickr.com/1200/800/hallgrimskirkja"
echo "  d0-strip-harpa.jpg..."
curl -L -s -o "$IMG_DIR/d0-strip-harpa.jpg" "https://loremflickr.com/1200/800/harpa,reykjavik"
echo "  d0-strip-reykjavik.jpg..."
curl -L -s -o "$IMG_DIR/d0-strip-reykjavik.jpg" "https://loremflickr.com/1200/800/reykjavik,harbour"
echo "  d1-hero-gullfoss.jpg..."
curl -L -s -o "$IMG_DIR/d1-hero-gullfoss.jpg" "https://loremflickr.com/1200/800/gullfoss"
echo "  d1-strip-gullfoss.jpg..."
curl -L -s -o "$IMG_DIR/d1-strip-gullfoss.jpg" "https://loremflickr.com/1200/800/gullfoss,waterfall"
echo "  d1-strip-geysir.jpg..."
curl -L -s -o "$IMG_DIR/d1-strip-geysir.jpg" "https://loremflickr.com/1200/800/geyser,iceland"
echo "  d2-hero-jokulsarlon.jpg..."
curl -L -s -o "$IMG_DIR/d2-hero-jokulsarlon.jpg" "https://loremflickr.com/1200/800/jokulsarlon,boat"
echo "  d2-strip-jokulsarlon.jpg..."
curl -L -s -o "$IMG_DIR/d2-strip-jokulsarlon.jpg" "https://loremflickr.com/1200/800/jokulsarlon,sunset"
echo "  d3-hero-eastfjords.jpg..."
curl -L -s -o "$IMG_DIR/d3-hero-eastfjords.jpg" "https://loremflickr.com/1200/800/fjord,iceland"
echo "  d3-strip-eastfjords.jpg..."
curl -L -s -o "$IMG_DIR/d3-strip-eastfjords.jpg" "https://loremflickr.com/1200/800/fjord,road"
echo "  d3-strip-seydisfjordur.jpg..."
curl -L -s -o "$IMG_DIR/d3-strip-seydisfjordur.jpg" "https://loremflickr.com/1200/800/seydisfjordur"
echo "  d3-strip-vok.jpg..."
curl -L -s -o "$IMG_DIR/d3-strip-vok.jpg" "https://loremflickr.com/1200/800/geothermal,lake"
echo "  d4-hero-myvatn.jpg..."
curl -L -s -o "$IMG_DIR/d4-hero-myvatn.jpg" "https://loremflickr.com/1200/800/myvatn,iceland"
echo "  d4-strip-studlagil.jpg..."
curl -L -s -o "$IMG_DIR/d4-strip-studlagil.jpg" "https://loremflickr.com/1200/800/basalt,canyon"
echo "  d4-strip-hverir.jpg..."
curl -L -s -o "$IMG_DIR/d4-strip-hverir.jpg" "https://loremflickr.com/1200/800/volcanic,steam"
echo "  d4-strip-myvatn-baths.jpg..."
curl -L -s -o "$IMG_DIR/d4-strip-myvatn-baths.jpg" "https://loremflickr.com/1200/800/geothermal,pool"
echo "  d5-hero-husavik.jpg..."
curl -L -s -o "$IMG_DIR/d5-hero-husavik.jpg" "https://loremflickr.com/1200/800/husavik"
echo "  d5-strip-godafoss.jpg..."
curl -L -s -o "$IMG_DIR/d5-strip-godafoss.jpg" "https://loremflickr.com/1200/800/godafoss"
echo "  d5-strip-geosea.jpg..."
curl -L -s -o "$IMG_DIR/d5-strip-geosea.jpg" "https://loremflickr.com/1200/800/sea,bath,ocean"
echo "  d6-strip-snaefellsnes.jpg..."
curl -L -s -o "$IMG_DIR/d6-strip-snaefellsnes.jpg" "https://loremflickr.com/1200/800/snaefellsjokull"
echo "  d6-strip-arnarstapi.jpg..."
curl -L -s -o "$IMG_DIR/d6-strip-arnarstapi.jpg" "https://loremflickr.com/1200/800/iceland,cliff,arch"
echo "  d7-hero-hraunfossar.jpg..."
curl -L -s -o "$IMG_DIR/d7-hero-hraunfossar.jpg" "https://loremflickr.com/1200/800/hraunfossar"
echo "  d7-strip-river.jpg..."
curl -L -s -o "$IMG_DIR/d7-strip-river.jpg" "https://loremflickr.com/1200/800/iceland,waterfall,river"
echo "  d7-strip-reykjavik.jpg..."
curl -L -s -o "$IMG_DIR/d7-strip-reykjavik.jpg" "https://loremflickr.com/1200/800/reykjavik,aerial"
echo "  springs-hero.jpg..."
curl -L -s -o "$IMG_DIR/springs-hero.jpg" "https://loremflickr.com/1200/800/hot,spring,iceland"
echo "  spring-hrunalaug.jpg..."
curl -L -s -o "$IMG_DIR/spring-hrunalaug.jpg" "https://loremflickr.com/1200/800/hot,spring,natural"
echo "  spring-vok.jpg..."
curl -L -s -o "$IMG_DIR/spring-vok.jpg" "https://loremflickr.com/1200/800/infinity,pool,lake"
echo "  spring-myvatn.jpg..."
curl -L -s -o "$IMG_DIR/spring-myvatn.jpg" "https://loremflickr.com/1200/800/geothermal,mineral,water"
echo "  spring-geosea.jpg..."
curl -L -s -o "$IMG_DIR/spring-geosea.jpg" "https://loremflickr.com/1200/800/sea,geothermal,baths"
echo "  spring-fosslaug.jpg..."
curl -L -s -o "$IMG_DIR/spring-fosslaug.jpg" "https://loremflickr.com/1200/800/hot,spring,pool"
echo "  aurora-hero.jpg..."
curl -L -s -o "$IMG_DIR/aurora-hero.jpg" "https://loremflickr.com/1200/800/aurora,borealis,iceland"

echo ""
echo "✅ Done! All images downloaded to $IMG_DIR"
echo "Open Iceland_Family_Brochure_2026.html in your browser."